[
  {c:"#2b2c2e",t:"#ffffff",p:"DSA"},
  "f1\npower\n\n\n\n\n⎋",
  {c:"#e8e7e3",t:"#000000",a:0},
  "f2\nPt Sc\n\n\nQ\n\nQ",
  "f3\nSc Lk\n\n\nW\n\nW",
  "f4\nPause\n\n\nF\n\nE",
  "f5\n# Lk\n\n\nP\n\nR",
  "f6\nExec\n\n\nG\n\nT",
  "f7\nMenu\n\n\nJ\n\nY",
  "f8\nApp\n\n\nL\n\nU",
  "f9\n7\n\n\nU\n\nI",
  "f10\n8\n\n\nY\n\nO",
  {h2:0.75},
  "f11\n9\n\n\n;\n:\nP",
  {c:"#2b2c2e",t:"#ffffff",a:4},
  "f12\n/\n\n\n\n\n⇥\n⇤"
],
[
  {a:7},
  "⌃\nPower\n\n\n\n\n⎋",
  {c:"#e8e7e3",t:"#000000",a:0},
  "1\nVol -\n!\n\nA\n\nA",
  "2\nVol +\n@\n\nR\n\nS",
  "3\nMute\n#\n\nS\n\nD",
  "4\n⇪\n$\n\nT\n\nF",
  "5\nCancel\n%\n\nD\n\nG",
  "6\nUndo\n^\n\nH\n\nH",
  "7\nAgain\n&\n\nN\n\nJ",
  "8\n4\n*\n\nE\n\nK",
  "9\n5\n(\n\nI\n\nL",
  "0\n6\n)\n\nO\n\n;\n:",
  {c:"#2b2c2e",t:"#ffffff",a:4},
  "⌦\n*\n\n\n\n\n⌫"
],
[
  {a:7},
  "⌥\npower\n\n\n\n\n⎋",
  {c:"#e8e7e3",t:"#000000",a:0},
  "`\nInsert\n~\n\nZ\n\nZ",
  "-\nCut\n_\n\nX\n\nX",
  "=\nCopy\n+\n\nC\n\nC",
  "'\nPaste\n\"\n\nV\n\nV",
  "\"\n|\n'\n\\\nB\n\nB",
  "{\n(\n[\n9\nK\n\nN",
  "}\n)\n]\n0\nM\n\nM",
  "[\n1\n{\n\n,\n<\n,\n<",
  "]\n2\n}\n\n.\n>\n.\n>",
  "\\\n3\n/\n\n/\n?\n/\n?",{c:"#2b2c2e",t:"#ffffff",a:4},
  "\n-\n\n\n\n\n↩"
],
[
  {a:7},"○",
  "◆\npt sc\n\n\n\n\nq",
  "⌘\nsc lk\n\n\n\n\nw",
  "⇧\npause\n\n\n\n\ne",
  {c:"#c0472c",t:"#000000"},
  "⥥\nnum lk\n\n\n\n\nr",
  {c:"#e8e7e3",p:"DSA SPACE",a:4,w:2},
  "",
  {c:"#c0472c",p:"DSA",a:7},
  "⥣\napp\n\n\n\n\nu",
  {c:"#2b2c2e",t:"#ffffff",a:4},
  "↖\n0\n\n\n\n\n←",
  "⇟\n.\n\n\n\n\n↓",
  "⇞\n↵\n\n\n\n\n↑",
  "↘\n+\n\n\n\n\n→"
]
