[
  {c:"#c0c0c0",t:"#2b2c2e",p:"DSA",a:5},
  "F13\n!\n\n\n\n\nQ",
  "F14\n@\n\n\n\n\nW",
  "F15\n#\n\n\n\n\nF",
  "F16\n$\n\n\n\n\nP",
  "F17\n%\n\n\n\n\nG",
  "F18\n^\n\n\n\n\n' \"",
  "F19\n&\n\n\n\n\n\\ |",
  "F20\n*\n\n\n\n\nJ",
  "F21\n(\n\n\n\n\nL",
  "F22\n)\n\n\n\n\nU",
  "F23\n_\n\n\n\n\nY",
  "F24\n+\n\n\n\n\n; :"
],
[
  "F1\n1\n\n\n\n\nA",
  "F2\n2\n\n\n\n\nR",
  "F3\n3\n\n\n\n\nS",
  "F4\n4\n\n\n\n\nT",
  "F5\n5\n\n\n\n\nD",
  {c:"#2b2c2e",t:"#c0c0c0"},
  "F6\n6\n\n\n\n\n⇥",
  "F7\n7\n\n\n\n\n⎋",
  {c:"#c0c0c0",t:"#2b2c2e"},
  "F8\n8\n\n\n\n\nH",
  "F9\n9\n\n\n\n\nN",
  "F10\n0\n\n\n\n\nE",
  "F11\n-\n\n\n\n\nI",
  "F12\n=\n\n\n\n\nO"
],
[
  "Menu\n\n\n\n\n\nZ",
  "Cut\n\n\n\n\n\nX",
  "Copy\n`\n\n\n\n\nC",
  "Paste\n~\n\n\n\n\nV",
  "⌦\n\n\n\n\n\nB",
  {c:"#2b2c2e",t:"#c0c0c0"},
  "\n\n\n\n\n\n⌫",
  "\n\n\n\n\n\n↩",
  {c:"#c0c0c0",t:"#2b2c2e"},
  "⇪\n\n\n\n\n\nK",
  "Ins\n[\n\n\n\n\nM",
  "Pt Sc\n]\n\n\n\n\n, <",
  "Sc Lk\n{\n\n\n\n\n. >",
  "Pause\n}\n\n\n\n\n/ ?"
],
[
  {c:"#2b2c2e",t:"#c0c0c0"},
  "\n\n\n\n\n\n⌃",
  "\n\n\n\n\n\n⌥",
  "\n\n\n\n\n\n⌘",
  "\n\n\n\n\n\n⇧",
  {c:"#c0472c"},
  "\n\n\n\n\n\n⥥",
  {c:"#2b2c2e",w:2},
  "\n\n\n\n\n\n␣",
  {c:"#c0472c"},
  "\n\n\n\n\n\n⥣",
  {c:"#2b2c2e"},
  "Mute\n↖\n\n\n\n\n←",
  "Vol-\n⇟\n\n\n\n\n↓",
  "Vol+\n⇞\n\n\n\n\n↑",
  "P/P\n↘\n\n\n\n\n→"
]