{backcolor:"#ffffff"},
[
  {c:"#2b2c2e",t:"#ffffff",p:"DSA",a:5,f:4},
  "f1\n` ~\n\n\n\n\n⇥",
  {c:"#e8e7e3",t:"#000000"},
  "f2\n1 !\n\n\n\n\nq",
  "f3\n2 @\n\n\n\n\nw",
  "f4\n3 #\n\n\n\n\nf",
  "f5\n4 $\n\n\n\n\np",
  "f6\n5 %\n\n\n\n\ng",
  "f7\n6 ^\n\n\n\n\nj",
  "f8\n7 &\n\n\n\n\nl",
  "f9\n8 *\n\n\n\n\nu",
  "f10\n9 (\n\n\n\n\ny",
  "f11\n0 )\n\n\n\n\n; :",
  {c:"#2b2c2e",t:"#ffffff"},
  "f12\n= +\n\n\n\n\n⌫"
],
[
  {c:"#b81b24"},
  "pwr\n\n\n\n\n\nesc",
  {c:"#e8e7e3",t:"#000000"},
  "\n\n\n\n\n\na",
  "\n\n\n\n\n\nr",
  "\n\n\n\n\n\ns",
  "\n\n\n\n\n\nt",
  "\n\n\n\n\n\nd",
  "\n\n\n\n\n\nh",
  "\n\n\n\n\n\nn",
  "\n\n\n\n\n\ne",
  "\n[ {\n\n\n\n\ni",
  "\n] }\n\n\n\n\no",
  {c:"#0075ad",t:"#ffffff"},
  "' \"\n- _\n\n\n\n\n↵"
],
[
  {c:"#2b2c2e"},
  "\n\n\n\n\n\n⇧",
  {c:"#e8e7e3",t:"#000000",a:7},
  "z",
  "x",
  "c",
  "v",
  "b",
  {a:5},
  "\n\n\n\n\n\nk",
  "\n\n\n\n\n\nm",
  "\n\n\n\n\n\n, <",
  "\n\n\n\n\n\n. >",
  "\n\\ |\n\n\n\n\n/ ?",
  {c:"#2b2c2e",t:"#ffffff"},
  "\n\n\n\n\n\n⇧"
],
[
  "\n\n\n\n\n\n°",
  "\n\n\n\n\n\n⌃",
  "\n\n\n\n\n\n⌥",
  "\n\n\n\n\n\n⌘",
  {c:"#c0472c"},
  "\n\n\n\n\n\n⇑",
  {c:"#e8e7e3",a:4,w:2},
  "",
  {c:"#c0472c",a:5},
  "\n\n\n\n\n\n⇓",
  {c:"#2b2c2e"},
  "\n\n\n\n\n\n←",
  "\n\n\n\n\n\n↓",
  "\n\n\n\n\n\n↑",
  "\n\n\n\n\n\n→"
]
